input/trace32_ad: use u64 instead of u32 for samplerate option
The variable type is already u64 so this is consistent now inside of
this module and also with the other input parsers using a samplerate
option.

This also fixes a crash when invoking PulseView with the "samplerate"
command line option because u32 is not yet included in C++ bindings:

$ pulseview -i /dev/null -I trace32_ad:samplerate=1
Exception: internal error