Enable C++17 language features
When trying to build on macOS Catalina with recent compilers
(GCC 10.2.0) and libraries (libsigc++ 3.0.6) installed through Homebrew,
the process croaked with "error: 'invoke' is not a member of 'std'".

It turned out that libsigc++ is telling us [1]:

> Compatible compilers must support C++17, such as the decltype(auto)
> specifier (from C++14) and std::invoke().

[1] https://github.com/libsigcplusplus/libsigcplusplus#compatibility