configure.ac: Temporarily disable Java bindings.
Those need a bugfix to make them build again:

  bindings/java/org/sigrok/core/classes/Context.java:92: error: method Context_create_analog_packet in class classesJNI cannot be applied to given types;
        long cPtr = classesJNI.Context_create_analog_packet(swigCPtr, this, ChannelVector.getCPtr(tempchannels), SWIGTYPE_p_float.getCPtr(data_pointer), num_samples, Quantity.getCPtr(mq), mq, Unit.getCPtr(unit), unit, QuantityFlagVector.getCPtr(mqflags), mqflags);
                              ^
    required: long,Context,Vector<Channel>,long,long,long,Quantity,long,Unit,long,QuantityFlagVector
    found: long,Context,long,long,long,long,Quantity,long,Unit,long,QuantityFlagVector
    reason: actual argument long cannot be converted to Vector<Channel> by method invocation conversion
  1 error
  Makefile:3352: recipe for target 'bindings/java/sigrok-core.jar' failed